FROM apache/airflow:2.9.0

USER airflow

RUN pip install --no-cache-dir \
    faker \
    psycopg2-binary \
    pandas \
    python-dotenv \
    dbt-postgres

RUN mkdir -p /home/airflow/.dbt
COPY dbt_profiles.yml /home/airflow/.dbt/profiles.yml